// Os 34 atributos basicos do modelo de Kljajic Borstnar e Pucihar (2021),
// na ordem fixa do artigo original. Fonte unica de verdade: servidor e cliente
// buscam esta lista via GET /api/attrs -- nunca duplicar ou reescrever em outro lugar.
const ATTRS = [
  {
    id: "Blockchain",
    descricao: "[A] Atrib 1 — Tabela 1 do artigo. Quatro niveis: nao usa / sem necessidade / planeja / utiliza.",
    niveis: ["Nao.utiliza", "Sem.necessidade", "Planeja", "Utiliza"],
    dimensao: "Capacidade Digital",
    grupo: "A11.TEC.AVANCADAS",
  },
  {
    id: "Industria.4.0",
    descricao: "[A] Atrib 2 — IoT, automacao avancada, gemeo digital. Quatro niveis.",
    niveis: ["Nao", "Sem.necessidade", "Planeja", "Utiliza"],
    dimensao: "Capacidade Digital",
    grupo: "A11.TEC.AVANCADAS",
  },
  {
    id: "Analise.de.Dados",
    descricao: "[A] Atrib 3 — Tabela 1 do artigo. Escala: No/Partial/BI/Advanced. Adaptada ao portugues.",
    niveis: ["Nao", "Parcial", "BI", "Avancado"],
    dimensao: "Capacidade Digital",
    grupo: "A11.TEC.AVANCADAS",
  },
  {
    id: "Midias.Sociais",
    descricao: "[A] Atrib 4 — redes sociais. Quatro niveis.",
    niveis: ["Nao", "Minimo", "Relacionamento", "Completo"],
    dimensao: "Capacidade Digital",
    grupo: "A12.SMACIT",
  },
  {
    id: "Mobile",
    descricao: "[A] Atrib 5 — tecnologias moveis. Quatro niveis.",
    niveis: ["Nao", "Processos.Internos", "Experiencia.Cliente", "Completo"],
    dimensao: "Capacidade Digital",
    grupo: "A12.SMACIT",
  },
  {
    id: "Cloud",
    descricao: "[A] Atrib 6 — computacao em nuvem. Quatro niveis.",
    niveis: ["Nao.utiliza", "Uso.minimo", "Uso.moderado", "Uso.estrategico"],
    dimensao: "Capacidade Digital",
    grupo: "A12.SMACIT",
  },
  {
    id: "Software.Gestao",
    descricao: "[A] Atrib 7 — Business software solutions. Quatro niveis.",
    niveis: ["Nao", "Parcial", "Basico", "Completo"],
    dimensao: "Capacidade Digital",
    grupo: "A13.TEC.BASICAS",
  },
  {
    id: "Ambiente.Digital.Trabalho",
    descricao: "[A] Atrib 8 — Digital workplace. Quatro niveis.",
    niveis: ["Nao", "Software.Negocio", "Parcial", "Completo"],
    dimensao: "Capacidade Digital",
    grupo: "A13.TEC.BASICAS",
  },
  {
    id: "Investimento.TI",
    descricao: "[A] Atrib 9 — % investments in IT. Quatro niveis.",
    niveis: ["Menos.1pct", "Entre.1.3pct", "Mais.3pct", "Lideranca.Digital"],
    dimensao: "Capacidade Digital",
    grupo: "A2.PAPEL.INFORMATICA",
  },
  {
    id: "Investimentos.Planejados",
    descricao: "[A] Atrib 10 — Planned investments. Quatro niveis.",
    niveis: ["Sem.Planejamento", "Mercado", "Estrategico", "Inovacao.Continua"],
    dimensao: "Capacidade Digital",
    grupo: "A2.PAPEL.INFORMATICA",
  },
  {
    id: "Departamento.TI",
    descricao: "[A] Atrib 11 — IT department. Quatro niveis.",
    niveis: ["Terceirizado", "Proprio.Terceirizado", "TI.Propria", "Estrategico"],
    dimensao: "Capacidade Digital",
    grupo: "A2.PAPEL.INFORMATICA",
  },
  {
    id: "Proposta.Valor",
    descricao: "[A] Atrib 12 — Value proposition. Quatro niveis.",
    niveis: ["Nao", "Parcial", "Impacto.Digital", "Digital.no.Core"],
    dimensao: "Capacidade Digital",
    grupo: "A3.MODELO.NEGOCIO",
  },
  {
    id: "CRM",
    descricao: "[A] Atrib 13 — CRM. Quatro niveis.",
    niveis: ["Nao", "Dados.Cliente", "CRM.Social", "Estrategico"],
    dimensao: "Capacidade Digital",
    grupo: "A31.CLIENTES",
  },
  {
    id: "Canais.Digitais",
    descricao: "[A] Atrib 14 — Digital channels. Quatro niveis.",
    niveis: ["Nao", "Site", "Loja.Virtual", "Totalmente.Integrado"],
    dimensao: "Capacidade Digital",
    grupo: "A31.CLIENTES",
  },
  {
    id: "Novos.Mercados",
    descricao: "[A] Atrib 15 — Customer segments — new markets. Quatro niveis.",
    niveis: ["Nao", "Parcial", "Uso.Pleno", "Modelo.Digital.Nativo"],
    dimensao: "Capacidade Digital",
    grupo: "A31.CLIENTES",
  },
  {
    id: "Processos.Chave",
    descricao: "[A] Atrib 16 — Key processes. Quatro niveis.",
    niveis: ["Nao", "Parcial", "Totalmente", "Automatizado"],
    dimensao: "Capacidade Digital",
    grupo: "A32.ATIVIDADES",
  },
  {
    id: "Relacao.Parceiros",
    descricao: "[A] Atrib 17 — Suppliers and partners relationship. Quatro niveis.",
    niveis: ["Nao", "EDI", "Sistemas.Conectados", "Cadeia.Integrada"],
    dimensao: "Capacidade Digital",
    grupo: "A32.ATIVIDADES",
  },
  {
    id: "Receitas.Custos",
    descricao: "[A] Atrib 18 — Revenues-Costs. Quatro niveis.",
    niveis: ["Nao", "Reducao.Custos", "Novas.Receitas", "Novo.Modelo.Negocio"],
    dimensao: "Capacidade Digital",
    grupo: "A32.ATIVIDADES",
  },
  {
    id: "Dados.Estrategia",
    descricao: "[A] Atrib 19 — Data (strategy). Quatro niveis.",
    niveis: ["Basico", "Operacional", "Gestao.Integrada", "Recurso.Estrategico"],
    dimensao: "Capacidade Digital",
    grupo: "A4.ESTRATEGIA",
  },
  {
    id: "Ciberseguranca",
    descricao: "[A] Atrib 20 — Cyber Security. Quatro niveis.",
    niveis: ["Nao", "Ciente.Planejando", "Estrategico", "Certificado.Auditado"],
    dimensao: "Capacidade Digital",
    grupo: "A4.ESTRATEGIA",
  },
  {
    id: "Estrategia.Digital",
    descricao: "[A] Atrib 21 — Digital (strategy). Quatro niveis.",
    niveis: ["Nao", "Ciente.Planejando", "Parcial", "Sim"],
    dimensao: "Capacidade Digital",
    grupo: "A4.ESTRATEGIA",
  },
  {
    id: "Engajamento",
    descricao: "[A] Atrib 22 — Engagement. Quatro niveis.",
    niveis: ["Limitado", "Moderado", "Completo", "Protagonista"],
    dimensao: "Capacidade Organizacional",
    grupo: "B11.CULTURA.COLABORADOR",
  },
  {
    id: "Aceitacao.Mudancas",
    descricao: "[A] Atrib 23 — Accepting changes. Quatro niveis.",
    niveis: ["Critico", "Aceita", "Curioso", "Entusiasmado"],
    dimensao: "Capacidade Organizacional",
    grupo: "B11.CULTURA.COLABORADOR",
  },
  {
    id: "Competencias.Digitais",
    descricao: "[A] Atrib 24 — Digital competences. Quatro niveis.",
    niveis: ["Inexistente", "Basico", "Avancado", "Referencia.Digital"],
    dimensao: "Capacidade Organizacional",
    grupo: "B12.GESTAO.RH",
  },
  {
    id: "Gestao.Talentos",
    descricao: "[A] Atrib 25 — Talent management. Quatro niveis.",
    niveis: ["Nao", "Basico", "Investe.Ativamente", "Estrategico"],
    dimensao: "Capacidade Organizacional",
    grupo: "B12.GESTAO.RH",
  },
  {
    id: "Educacao.Treinamento",
    descricao: "[A] Atrib 26 — Education and training. Quatro niveis.",
    niveis: ["Nao", "Ocasional", "Continuo", "Estrategico"],
    dimensao: "Capacidade Organizacional",
    grupo: "B12.GESTAO.RH",
  },
  {
    id: "Autonomia",
    descricao: "[A] Atrib 27 — Autonomy. Quatro niveis.",
    niveis: ["Restrita", "Moderado", "Completo", "Autogerenciado"],
    dimensao: "Capacidade Organizacional",
    grupo: "B2.CULTURA.ORGANIZACIONAL",
  },
  {
    id: "Comunicacao",
    descricao: "[A] Atrib 28 — Communication. Quatro niveis.",
    niveis: ["Interna.Area", "Entre.Departamentos", "Aberta", "Colaborativa.Digital"],
    dimensao: "Capacidade Organizacional",
    grupo: "B2.CULTURA.ORGANIZACIONAL",
  },
  {
    id: "Colaboracao",
    descricao: "[A] Atrib 29 — Collaboration. Quatro niveis.",
    niveis: ["Nao.Incentivada", "Incentivada", "Completo", "Co.Criacao.Estrategica"],
    dimensao: "Capacidade Organizacional",
    grupo: "B2.CULTURA.ORGANIZACIONAL",
  },
  {
    id: "Capacidade.Inovar",
    descricao: "[A] Atrib 30 — Innovativeness. Quatro niveis.",
    niveis: ["Nao.Incentivada", "Incentivada", "Suporte.Pleno", "Cultura.Inovacao"],
    dimensao: "Capacidade Organizacional",
    grupo: "B2.CULTURA.ORGANIZACIONAL",
  },
  {
    id: "Agilidade",
    descricao: "[A] Atrib 31 — Agility. Quatro niveis.",
    niveis: ["Lenta", "Moderado", "Agil", "Preditiva"],
    dimensao: "Capacidade Organizacional",
    grupo: "B3.GESTAO",
  },
  {
    id: "Lideranca",
    descricao: "[A] Atrib 32 — Leadership. Quatro niveis.",
    niveis: ["Autoritaria", "Participativa", "Transformacional", "Distribuida.Digital"],
    dimensao: "Capacidade Organizacional",
    grupo: "B3.GESTAO",
  },
  {
    id: "Tomada.Decisao",
    descricao: "[A] Atrib 33 — Decision-making. Quatro niveis.",
    niveis: ["Intuitiva", "Analitica", "Data.Driven", "Preditiva.IA"],
    dimensao: "Capacidade Organizacional",
    grupo: "B3.GESTAO",
  },
  {
    id: "Propensao.Risco",
    descricao: "[A] Atrib 34 — Risk taking. Quatro niveis.",
    niveis: ["Averse", "Neutro", "Busca.Riscos", "Empreendedor.Digital"],
    dimensao: "Capacidade Organizacional",
    grupo: "B3.GESTAO",
  },
];

module.exports = { ATTRS };